name: streaker
description: Focuses on the power of streaks for habit formation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  firebase_core: ^2.30.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.0.0
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  auth_buttons: ^3.0.2
  firebase_auth: ^4.19.2

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_gen: ^5.4.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: ic_launcher
  image_path: assets/images/logo.png

flutter_native_splash:
  color: "#6A3DE8" # primary color
  image: assets/images/logo.png

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
