name: streaker
description: "Habit Tracker App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^13.0.0
  get_it: ^8.0.0
  go_router: ^14.3.0
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.6.0
  hugeicons: ^0.0.7

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
