# Create .env file and add variables
touch .env 

echo \
"
# Appwrite
APPWRITE_ENDPOINT=$APPWRITE_ENDPOINT
APPWRITE_PROJECT=$APPWRITE_PROJECT

# Firebase
FIREBASE_API_KEY=$FIREBASE_API_KEY
FIREBASE_APP_ID=$FIREBASE_APP_ID
FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
SENTRY_DSN=$SENTRY_DSN
" >> .env

# Setup google-services.json
touch android/app/google-services.json
echo $GOOGLE_SERVICES_FILE >> android/app/google-services.json
